export const ACTIVITY_URI='ui://codx-remote/activity-v1.html';
export const ACTIVITY_META={ui:{resourceUri:ACTIVITY_URI},'openai/toolInvocation/invoking':'Conectando ao seu computador…','openai/toolInvocation/invoked':'Codx Remote conectado'};
export function activityResource(backend){
  const logo=backend+'/assets/codx-symbol.png';
  const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
    *{box-sizing:border-box}body{margin:0;padding:16px;font-family:system-ui,sans-serif;background:var(--color-background-primary,#10151d);color:var(--color-text-primary,#e8eef9)}.card{border:1px solid var(--color-border-secondary,#2e3a50);border-radius:16px;padding:18px}.head{display:flex;align-items:center;gap:14px}.logo{width:45px;height:45px;object-fit:contain}.busy .logo{animation:breathe 2s ease-in-out infinite}h2{font-size:14px;margin:0 0 5px}p{font-size:11px;color:var(--color-text-secondary,#8596b0);margin:0}.dot{width:6px;height:6px;background:#68ddb1;border-radius:50%;display:inline-block;margin-right:5px}.devices{display:grid;gap:8px;margin-top:16px}.row{display:flex;align-items:center;justify-content:space-between;font-size:11px;padding:10px;border-radius:8px;background:var(--color-background-secondary,#182131)}.status{color:#71c6a3}.task{font-size:11px;margin-top:13px;color:var(--color-text-secondary,#a1b1cb)}.controls{display:flex;justify-content:space-between;align-items:center;margin-top:14px}button{font:11px system-ui;color:var(--color-text-primary,#bbd1fa);background:transparent;border:1px solid var(--color-border-secondary,#374b6c);border-radius:7px;padding:7px 11px;cursor:pointer}button:focus-visible{outline:2px solid #83b1ff}small{font-size:10px;color:var(--color-text-secondary,#788aa6)}@keyframes breathe{50%{transform:translateY(-3px);filter:drop-shadow(0 0 10px #80aaff88)}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}
  </style></head><body><div class="card" id="card"><div class="head"><img class="logo" src="${logo}" alt="Codx Remote"><div><h2>Codx Remote</h2><p id="summary">Conectando à atividade do seu PC…</p></div></div><div class="devices" id="devices"></div><div class="task" id="task" role="status"></div><div class="controls"><small id="updated">Aguardando dados</small><button id="refresh">Atualizar</button></div></div><script>
    const pending=new Map();let seq=0,ready=false,inflight=false,timer=null;
    const $=id=>document.getElementById(id);
    function send(method,params){const id=++seq;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(id);reject(Error('Host indisponível'))},8000);pending.set(id,{resolve,reject,timeout});parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
    function notify(method,params){parent.postMessage({jsonrpc:'2.0',method,params},'*')}
    function render(data){if(!data)return;const devices=data.devices||[];const active=data.activeTools||[];$('card').classList.toggle('busy',active.length>0);$('summary').textContent=active.length?'Trabalhando no seu computador':devices.some(d=>d.online)?'Seu computador está conectado':'Nenhum computador online';$('devices').replaceChildren();for(const d of devices){const row=document.createElement('div');row.className='row';const name=document.createElement('span');name.textContent=d.deviceName;const status=document.createElement('span');status.className='status';status.textContent=d.revoked?'Revogado':d.online?'● Online':'○ Offline';row.append(name,status);$('devices').append(row)}$('task').textContent=active.length?active.map(a=>'Em execução: '+a.tool).join(' · '):'Pronto para sua próxima tarefa.';$('updated').textContent='Atualizado às '+new Date().toLocaleTimeString('pt-BR');notify('ui/notifications/size-changed',{height:document.body.scrollHeight,width:document.body.scrollWidth})}
    async function refresh(){if(!ready||inflight)return;inflight=true;try{const result=await send('tools/call',{name:'show_activity',arguments:{}});render(result.structuredContent)}catch{$('updated').textContent='Use Atualizar para tentar novamente.'}finally{inflight=false}}
    addEventListener('message',event=>{if(event.source!==parent||event.data?.jsonrpc!=='2.0')return;const msg=event.data;if(msg.id!==undefined&&!msg.method&&pending.has(msg.id)){const p=pending.get(msg.id);clearTimeout(p.timeout);pending.delete(msg.id);msg.error?p.reject(msg.error):p.resolve(msg.result);return}if(msg.method==='ui/notifications/tool-result')render(msg.params?.structuredContent);if(msg.method==='ui/notifications/tool-cancelled'){$('card').classList.remove('busy');$('task').textContent='Operação cancelada.'}if(msg.method==='ui/resource-teardown'){clearInterval(timer);parent.postMessage({jsonrpc:'2.0',id:msg.id,result:{}},'*')}});
    $('refresh').onclick=refresh;
    if(parent!==window)send('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'Codx Remote Activity',version:'0.9.0'},appCapabilities:{availableDisplayModes:['inline']}}).then(()=>{ready=true;notify('ui/notifications/initialized',{});timer=setInterval(()=>{if(!document.hidden)refresh()},5000);refresh()}).catch(()=>{$('updated').textContent='Este cartão precisa de um cliente MCP Apps.'});
  </script></body></html>`;
  return {uri:ACTIVITY_URI,mimeType:'text/html;profile=mcp-app',text:html,_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[backend]}},'openai/ui':{availableDisplayModes:['inline'],preferredDisplayMode:'inline'}}};
}
